### PR TITLE
Add test files

### PR DESCRIPTION
**Pull request by warenlg**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
Looks like you need to rebase; besides, you should copy-paste and adapt `.coverage.rc` from e.g. ast2vec.

**Comment by warenlg** [comment]
Ok, and should I still work on tests branch concerning this PR or move to master ?

**Comment by vmarkovtsev** [comment]
@warenlg Whatever you find is convenient for you - it's your local branch.

**Comment by vmarkovtsev** [comment]
@warenlg Please rebase on master and get rid of the last commit

**Comment by warenlg** [comment]
After resolving a conflict, I don't manage to squash this stupid last commit "Merge branch 'master' into tests"
Actually It seems the reason is because I just resolved the conflict directly on github
It seems better now

**Comment by vmarkovtsev** [comment]
@dpordomingo This is a real hard use case, you could include it into the lesson.

**Comment by warenlg** [comment]
I gave up and just reset --hard HEAD^ and resolve the conflict in master

**Comment by vmarkovtsev** [comment]
@warenlg Any chance you get rid of "Merge pull request #4 from warenlg/master" too?

**Comment by warenlg** [comment]
Can I squash commits you are the author ? because I think for that reason it does not appear in the git rebase -i head^^^ history

**Comment by vmarkovtsev** [comment]
Do whatever you find suitable

**Comment by vmarkovtsev** [comment]
@warenlg Ping

**Pull request merged**
