### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by warenlg**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
@warenlg Your tests score 0% coverage, need to fix

**Comment by warenlg** [comment]
This command ran the tests on my pc but not in travis
```
python3 -m unittest discover shcomplete/
```

**Comment by warenlg** [comment]
It impacts only the coverage of repos.py even though I 've committed in this PR tests on tries : why the coverage of tfdf.y does not change ? 
Or maybe it is but the file is not found in the report

**Comment by warenlg** [comment]
Ok no it is fine,

**Pull request merged**
